name: iOS CI Example

on: 
  push: 
    path: 
      - '**/*.swift'

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging
      - name: run_dev
        run: fastlane dev p12_pw:${{ secrets.P12_PW }}